### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by profmaad** [janestreet/jane-build#1]
Any chance for some instructions on how to use this?

After installing, I only get as far as 

> Can't find 'jengaroot.ml' or 'jenga.conf' in start-dir or any ancestor dir

**Comment by ghost** [comment]
Yes, we'll add some documentation. There is none currently because it is still a work in progress and many things don't work well. We'll add the doc as the system becomes more usable

**Comment by samdk** [comment]
I get that error when running jenga, but running "jane-build" instead works fine.

**Comment by ghost** [comment]
@profmaad can you confirm that you get this error when using `jenga` and not `jane-build`? `jenga` requires some rules while `jane-build` has all the rules statically linked in

**Comment by profmaad** [comment]
I got this error when trying to put `jenga` and `jenga-rules` together, which was solved by just using `jane-build`. This is solved for me.
