### ISSUE TITLE
jane-build silently ignores jbuild files which aren't in subdirectories

### ISSUE THREAD

**Issue by samdk** [janestreet/jane-build#2]
I had a directory structure that looked like

REPO_ROOT/
REPO_ROOT/example.ml
REPO_ROOT/jbuild

I ran jane-build (with cwd=REPO_ROOT) and it exited 0 but did nothing. After moving example.ml and jbuild under a src/ subdirectory things work fine.

**Comment by hhugo** [comment]
jane-build is no longer supported, please use https://github.com/ocaml/dune instead
