### ISSUE TITLE
used for ecaml through opam....

### ISSUE THREAD

**Issue by houndofsound** [janestreet/jane-build#4]
...as the ecaml readme says. 
but how do I get this through opam?
I tried 
   'opam repo add js-github git+https://github.com/janestreet/jane-build.git'
- that address is in the dev-repo field of the jane-build.opam file.

then this:
   'opam repo add js-github https://github.com/janestreet/jane-build.git'

and this:
   'opam repo add js-github https://github.com/janestreet/jane-build'

all to no avail.
what's the trick?

**Comment by ghost** [comment]
Ah, jane-build is no longer maintained. It's no longer relevant now that Jbuilder/Dune exist.

Jbuilder now support linking shared objects, so it's possible to create ecaml plugin with Jbuilder. The doc of ecaml needs to be updated.
